services:
  ai-api:
    build: .
    container_name: ai-core-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./logs:/app/logs
      - ./cache:/app/cache
      - ./models:/app/models
    depends_on:
      - redis
    networks:
      - ai-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ai-core-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: ai-core-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ai-api
    networks:
      - ai-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  ai-network:
    driver: bridge 